### PR TITLE
update Type for Contact

### PR DESCRIPTION
**Pull request by dns2utf8**

### CODE REVIEW

**Comment by dns2utf8** [comment]
This type error had been crashing my Bot, so I am looking forward for the api-update.

Currently we are using this in the Cargo.toml

    telegram-bot = { git = "https://github.com/dns2utf8/telegram-bot.git", branch = "fix_types" }

**Comment by dns2utf8** [comment]
Hi,

I had to restrict the Version of url to "0.2" so it would build again.

**Comment by knsd** [comment]
Lucas, do you still want to maintain this crate?

**Comment by LukasKalbertodt** [comment]
I'm very sorry for not maintaining this crate properly. I actually want to be the maintainer of this crate, but it's probably beneficial for the community to give it away.

@knsd Please contact me privately for now -- you can find my email on my GitHub account :)

**Pull request merged**
