### PR TITLE
Updated to hyper 0.9, url 1.2 and multipart 0.8

### PR DESCRIPTION
**Pull request by White-Oak**
Updated dependencies

### CODE REVIEW

**Comment by dns2utf8** [comment]
I think we should merge this until the rewrite is ready.

**Comment by White-Oak** [comment]
@dns2utf8 it would be nice also to issue a release upon updatinf dependencies. Currently, this crate forces users to download two versions of crates, and that causes bugs sometimes.

**Comment by White-Oak** [comment]
@LukasKalbertodt can you publish 0.4.3 with these updates? So crates.io version would have new dependencies.

**Comment by LukasKalbertodt** [comment]
@White-Oak Sorry for the late response. If I remember correctly we treat dependency version updates as breaking change, didn't we? I am pretty sure it is a breaking change....

So bump telegram-bot to 0.5.0?

**Comment by dns2utf8** [comment]
I agree, 0.5.0 seems fair.

**Comment by White-Oak** [comment]
Well, yeah, why not

**Comment by LukasKalbertodt** [comment]
I bumped the version and [published it](https://crates.io/crates/telegram-bot).

I also added a big warning to the README to show the status of this library. Brighter times will come, I'm sure of that 🌈 😛

**Comment by dns2utf8** [comment]
:+1:

**Pull request merged**
